// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(35,25,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(13,92,2^(33.647746))
// 
// Ring
// degree d = 64
// modulus q = 36028797018964597, log(q) ~ 55.0
// factors q = q1
// 
// Compression
// D = 10
// gamma = 514206, log(gamma) ~ 18.971987
// 
// Dimensions of secrets
// s1: m1 = 32
// m: l = 0
// s2: m2 = 60
// 
// Size of secrets
// l2(s1) <= alpha = 46.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [32], bounds: [45.254834])
// approximate infinity: yes (psi: 3355.8719, dimension: 16, bound: 1024.5)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 101580.8, log(stdev1/1.55) = 16.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 3174.4, log(stdev3/1.55) = 11.0
// stdev4 = 101580.8, log(stdev4/1.55) = 16.0
// 
// Repetition rate
// M1 = 2.3693196
// M2 = 2.5437218
// M3 = 1.0359469
// M4 = 1.0172873
// total = 6.3514724
// 
// Security
// MSIS dimension: 13
// MSIS root hermite factor: 1.0042966
// MLWE dimension: 35
// MLWE root hermite factor: 1.0043312
// 
// Proof size
// ~ 23.1894531250000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {36028797018964597UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 1, 0}};
static const limb_t _param_qminus1_limbs[] = {36028797018964596UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 1, 0}};
static const limb_t _param_m_limbs[] = {70066854566UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 1, 0}};
static const limb_t _param_mby2_limbs[] = {35033427283UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 1, 0}};
static const limb_t _param_gamma_limbs[] = {514206UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 1, 0}};
static const limb_t _param_gammaby2_limbs[] = {257103UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 1, 0}};
static const limb_t _param_pow2D_limbs[] = {1024UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 1, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {512UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 1, 0}};
static const limb_t _param_Bsq_limbs[] = {100800248132613UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 2, 0}};
static const limb_t _param_scM1_limbs[] = {2804632486965449207UL, 6812745002331132667UL, 2UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {14597513304372987885UL, 10029897663603524287UL, 2UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {8893015289224868487UL, 663103872151883249UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {15597524626124661798UL, 318894792362578700UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {10318658929UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 2, 0}};
static const limb_t _param_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 2, 0}};
static const limb_t _param_stdev3sq_limbs[] = {10076815UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 2, 0}};
static const limb_t _param_stdev4sq_limbs[] = {10318658929UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 2, 0}};
static const limb_t _param_inv2_limbs[] = {18014398509482298UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 1, 1}};
static const limb_t _param_inv4_limbs[] = {9007199254741149UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 1, 1}};
static const unsigned int _param_n[1] = {32};
static const limb_t _param_Bz3sqr_limbs[] = {6938266263UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 2, 0}};
static const limb_t _param_Bz4_limbs[] = {1625292UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 1, 0}};
static const limb_t _param_Pmodq_limbs[] = {15312922996381304UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 1, 1}};
static const limb_t _param_l2Bsq0_limbs[] = {2048UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 1, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {16149626802336294UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 1, 0}};
static const limb_t _param_Ppmodq_1_limbs[] = {16149626797846746UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 1, 0}};
static const limb_t _param_Ppmodq_2_limbs[] = {16149626793674994UL};
static const int_t _param_Ppmodq_2 = {{(limb_t *)_param_Ppmodq_2_limbs, 1, 0}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1, _param_Ppmodq_2};
static const polyring_t _param_ring = {{_param_q, 64, 56, 6, moduli_d64, 3, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 10, 0, 37 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 33, 60, 0, 12, 13, _param_Bsq, 1, 8, 5, 140, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 33, 60, 9, 3, 13, _param_Bsq, 1, 8, 5, 140, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 33, 60, 11, 1, 13, _param_Bsq, 1, 8, 5, 140, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 4}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 0, _param_n, 16, 1, 33, 2, 11, _param_scM3, _param_stdev3sq, 2, 16, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 23746UL }};

static const unsigned int param_Es0[32] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31};
static const unsigned int *param_Es[1] = { param_Es0, };
static const unsigned int param_Es_nrows[1] = {32};

static const limb_t param_p_limbs[] = {4294962689UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 1, 0}};
static const limb_t param_pinv_limbs[] = {14960510030049216UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 1, 0}};
static const unsigned int param_s1_indices[8] = {0, 1, 2, 3, 4, 5, 6, 7};
static const lin_params_t param = {{ _param, 256, param_p, param_pinv, 4, param_s1_indices, 8, NULL, 0,  NULL, 0, param_Es, param_Es_nrows, NULL, NULL }};

