// auto-generated by lnp-tbox.sage from ../demos/kyber512-secrets/lnp-params-kyber.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(23,31,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(19,70,2^(32.565606))
// 
// Ring
// degree d = 64
// modulus q = 34359738701, log(q) ~ 35.0
// factors q = q1
// 
// Compression
// D = 8
// gamma = 113050, log(gamma) ~ 16.786601
// 
// Dimensions of secrets
// s1: m1 = 16
// m: l = 0
// s2: m2 = 54
// 
// Size of secrets
// l2(s1) <= alpha = 43.111019
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// exact infinity: no
// exact euclidean: yes (dimensions: [16], bounds: [43.111019])
// approximate infinity: yes (psi: 2237.5535, dimension: 8, bound: 768.27005)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 101580.8, log(stdev1/1.55) = 16.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 3174.4, log(stdev3/1.55) = 11.0
// stdev4 = 50790.4, log(stdev4/1.55) = 15.0
// 
// Repetition rate
// M1 = 2.2477993
// M2 = 2.316982
// M3 = 1.0326705
// M4 = 1.0393064
// total = 5.5896623
// 
// Security
// MSIS dimension: 19
// MSIS root hermite factor: 1.0043273
// MLWE dimension: 23
// MLWE root hermite factor: 1.0042416
// 
// Proof size
// ~ 16.5605468750000 KiB
// 
// 23 bit moduli for degree 64: [8386817, 8386177, 8385281, 8384641]
// bit length of products: [22, 45, 68, 91]
// inverses: [1, 1664132, -20283, -3834820]

#include "lazer.h"
static const limb_t kyber_params_q_limbs[] = {34359738701UL};
static const int_t kyber_params_q = {{(limb_t *)kyber_params_q_limbs, 1, 0}};
static const limb_t kyber_params_qminus1_limbs[] = {34359738700UL};
static const int_t kyber_params_qminus1 = {{(limb_t *)kyber_params_qminus1_limbs, 1, 0}};
static const limb_t kyber_params_m_limbs[] = {303934UL};
static const int_t kyber_params_m = {{(limb_t *)kyber_params_m_limbs, 1, 0}};
static const limb_t kyber_params_mby2_limbs[] = {151967UL};
static const int_t kyber_params_mby2 = {{(limb_t *)kyber_params_mby2_limbs, 1, 0}};
static const limb_t kyber_params_gamma_limbs[] = {113050UL};
static const int_t kyber_params_gamma = {{(limb_t *)kyber_params_gamma_limbs, 1, 0}};
static const limb_t kyber_params_gammaby2_limbs[] = {56525UL};
static const int_t kyber_params_gammaby2 = {{(limb_t *)kyber_params_gammaby2_limbs, 1, 0}};
static const limb_t kyber_params_pow2D_limbs[] = {256UL};
static const int_t kyber_params_pow2D = {{(limb_t *)kyber_params_pow2D_limbs, 1, 0}};
static const limb_t kyber_params_pow2Dby2_limbs[] = {128UL};
static const int_t kyber_params_pow2Dby2 = {{(limb_t *)kyber_params_pow2Dby2_limbs, 1, 0}};
static const limb_t kyber_params_Bsq_limbs[] = {9758221246532UL, 0UL};
static const int_t kyber_params_Bsq = {{(limb_t *)kyber_params_Bsq_limbs, 2, 0}};
static const limb_t kyber_params_scM1_limbs[] = {17038006328090098925UL, 4571091034232081657UL, 2UL};
static const int_t kyber_params_scM1 = {{(limb_t *)kyber_params_scM1_limbs, 3, 0}};
static const limb_t kyber_params_scM2_limbs[] = {16587662842483214675UL, 5847285564330895312UL, 2UL};
static const int_t kyber_params_scM2 = {{(limb_t *)kyber_params_scM2_limbs, 3, 0}};
static const limb_t kyber_params_scM3_limbs[] = {12161179783098292072UL, 602664793072415986UL, 1UL};
static const int_t kyber_params_scM3 = {{(limb_t *)kyber_params_scM3_limbs, 3, 0}};
static const limb_t kyber_params_scM4_limbs[] = {1312238515711695265UL, 725074887436302413UL, 1UL};
static const int_t kyber_params_scM4 = {{(limb_t *)kyber_params_scM4_limbs, 3, 0}};
static const limb_t kyber_params_stdev1sq_limbs[] = {10318658929UL, 0UL};
static const int_t kyber_params_stdev1sq = {{(limb_t *)kyber_params_stdev1sq_limbs, 2, 0}};
static const limb_t kyber_params_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t kyber_params_stdev2sq = {{(limb_t *)kyber_params_stdev2sq_limbs, 2, 0}};
static const limb_t kyber_params_stdev3sq_limbs[] = {10076815UL, 0UL};
static const int_t kyber_params_stdev3sq = {{(limb_t *)kyber_params_stdev3sq_limbs, 2, 0}};
static const limb_t kyber_params_stdev4sq_limbs[] = {2579664732UL, 0UL};
static const int_t kyber_params_stdev4sq = {{(limb_t *)kyber_params_stdev4sq_limbs, 2, 0}};
static const limb_t kyber_params_inv2_limbs[] = {17179869350UL};
static const int_t kyber_params_inv2 = {{(limb_t *)kyber_params_inv2_limbs, 1, 1}};
static const limb_t kyber_params_inv4_limbs[] = {8589934675UL};
static const int_t kyber_params_inv4 = {{(limb_t *)kyber_params_inv4_limbs, 1, 1}};
static const unsigned int kyber_params_n[1] = {16};
static const limb_t kyber_params_Bz3sqr_limbs[] = {6938266263UL, 0UL};
static const int_t kyber_params_Bz3sqr = {{(limb_t *)kyber_params_Bz3sqr_limbs, 2, 0}};
static const limb_t kyber_params_Bz4_limbs[] = {812646UL};
static const int_t kyber_params_Bz4 = {{(limb_t *)kyber_params_Bz4_limbs, 1, 0}};
static const limb_t kyber_params_l2Bsq0_limbs[] = {1859UL};
static const int_t kyber_params_l2Bsq0 = {{(limb_t *)kyber_params_l2Bsq0_limbs, 1, 0}};
static const int_srcptr kyber_params_l2Bsq[] = {kyber_params_l2Bsq0};
static const polyring_t kyber_params_ring = {{kyber_params_q, 64, 36, 6, moduli_d64, 4, kyber_params_inv2}};
static const dcompress_params_t kyber_params_dcomp = {{ kyber_params_q, kyber_params_qminus1, kyber_params_m, kyber_params_mby2, kyber_params_gamma, kyber_params_gammaby2, kyber_params_pow2D, kyber_params_pow2Dby2, 8, 0, 19 }};
static const abdlop_params_t kyber_params_tbox = {{ kyber_params_ring, kyber_params_dcomp, 17, 54, 0, 12, 19, kyber_params_Bsq, 1, 8, 5, 140, 1, 16, kyber_params_scM1, kyber_params_stdev1sq, 2, 12, kyber_params_scM2, kyber_params_stdev2sq}};
static const abdlop_params_t kyber_params_quad_eval_ = {{ kyber_params_ring, kyber_params_dcomp, 17, 54, 9, 3, 19, kyber_params_Bsq, 1, 8, 5, 140, 1, 16, kyber_params_scM1, kyber_params_stdev1sq, 2, 12, kyber_params_scM2, kyber_params_stdev2sq}};
static const abdlop_params_t kyber_params_quad_many_ = {{ kyber_params_ring, kyber_params_dcomp, 17, 54, 11, 1, 19, kyber_params_Bsq, 1, 8, 5, 140, 1, 16, kyber_params_scM1, kyber_params_stdev1sq, 2, 12, kyber_params_scM2, kyber_params_stdev2sq}};
static const lnp_quad_eval_params_t kyber_params_quad_eval = {{ kyber_params_quad_eval_, kyber_params_quad_many_, 4}};
static const lnp_tbox_params_t kyber_params = {{ kyber_params_tbox, kyber_params_quad_eval, 0, kyber_params_n, 8, 1, 17, 2, 11, kyber_params_scM3, kyber_params_stdev3sq, 2, 15, kyber_params_scM4, kyber_params_stdev4sq, kyber_params_Bz3sqr, kyber_params_Bz4, &kyber_params_l2Bsq[0], kyber_params_inv4}};

