// auto-generated by abdlop-codegen.sage from ../tests/abdlop-params4.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-5)
// protocol is simulatable under MLWE(35,12,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-129.0)
// 
// Ring
// degree d = 64
// modulus q = 36028797018964597, log(q) ~ 55.0
// factors q = q1
// 
// Compression
// D = 7
// gamma = 57134, log(gamma) ~ 15.802062
// m = (q-1)/gamma = 630601691094, log(m) ~ 39.197938
// 
// Dimensions of secrets
// s1: m1 = 20
// m: l = 0
// s2: m2 = 47
// 
// Size of secrets
// l2(s1) <= alpha = 35.777088
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 50790.4, log(stdev1/1.55) = 15.0
// stdev2 = 50790.4, log(stdev2/1.55) = 15.0
// 
// Repetition rate
// M1 = 3.7571007
// M2 = 7.6376214
// total = 28.695312
// 
// Security
// MSIS dimension: 12
// MSIS root hermite factor: 1.0043552
// MLWE dimension: 35
// MLWE root hermite factor: 1.0043312
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t params4_q_limbs[] = {36028797018964597UL};
static const int_t params4_q = {{(limb_t *)params4_q_limbs, 1, 0}};
static const limb_t params4_qminus1_limbs[] = {36028797018964596UL};
static const int_t params4_qminus1 = {{(limb_t *)params4_qminus1_limbs, 1, 0}};
static const limb_t params4_m_limbs[] = {630601691094UL};
static const int_t params4_m = {{(limb_t *)params4_m_limbs, 1, 0}};
static const limb_t params4_mby2_limbs[] = {315300845547UL};
static const int_t params4_mby2 = {{(limb_t *)params4_mby2_limbs, 1, 0}};
static const limb_t params4_gamma_limbs[] = {57134UL};
static const int_t params4_gamma = {{(limb_t *)params4_gamma_limbs, 1, 0}};
static const limb_t params4_gammaby2_limbs[] = {28567UL};
static const int_t params4_gammaby2 = {{(limb_t *)params4_gammaby2_limbs, 1, 0}};
static const limb_t params4_pow2D_limbs[] = {128UL};
static const int_t params4_pow2D = {{(limb_t *)params4_pow2D_limbs, 1, 0}};
static const limb_t params4_pow2Dby2_limbs[] = {64UL};
static const int_t params4_pow2Dby2 = {{(limb_t *)params4_pow2Dby2_limbs, 1, 0}};
static const limb_t params4_Bsq_limbs[] = {24794706343945UL, 0UL};
static const int_t params4_Bsq = {{(limb_t *)params4_Bsq_limbs, 2, 0}};
static const limb_t params4_scM1_limbs[] = {6764829933787964209UL, 13966042373357930496UL, 3UL};
static const int_t params4_scM1 = {{(limb_t *)params4_scM1_limbs, 3, 0}};
static const limb_t params4_scM2_limbs[] = {10469613960975984156UL, 11762038037034343648UL, 7UL};
static const int_t params4_scM2 = {{(limb_t *)params4_scM2_limbs, 3, 0}};
static const limb_t params4_stdev1sq_limbs[] = {2579664732UL, 0UL};
static const int_t params4_stdev1sq = {{(limb_t *)params4_stdev1sq_limbs, 2, 0}};
static const limb_t params4_stdev2sq_limbs[] = {2579664732UL, 0UL};
static const int_t params4_stdev2sq = {{(limb_t *)params4_stdev2sq_limbs, 2, 0}};
static const limb_t params4_inv2_limbs[] = {18014398509482298UL};
static const int_t params4_inv2 = {{(limb_t *)params4_inv2_limbs, 1, 1}};
static const limb_t params4_Pmodq_limbs[] = {15312922996381304UL};
static const int_t params4_Pmodq = {{(limb_t *)params4_Pmodq_limbs, 1, 1}};
static const limb_t params4_Ppmodq_0_limbs[] = {16149626802336294UL};
static const int_t params4_Ppmodq_0 = {{(limb_t *)params4_Ppmodq_0_limbs, 1, 0}};
static const limb_t params4_Ppmodq_1_limbs[] = {16149626797846746UL};
static const int_t params4_Ppmodq_1 = {{(limb_t *)params4_Ppmodq_1_limbs, 1, 0}};
static const limb_t params4_Ppmodq_2_limbs[] = {16149626793674994UL};
static const int_t params4_Ppmodq_2 = {{(limb_t *)params4_Ppmodq_2_limbs, 1, 0}};

static const int_srcptr params4_Ppmodq[] = {params4_Ppmodq_0, params4_Ppmodq_1, params4_Ppmodq_2};
static const polyring_t params4_ring = {{params4_q, 64, 56, 6, moduli_d64, 3, params4_Pmodq, params4_Ppmodq, params4_inv2}};
static const dcompress_params_t params4_dcomp = {{ params4_q, params4_qminus1, params4_m, params4_mby2, params4_gamma, params4_gammaby2, params4_pow2D, params4_pow2Dby2, 7, 0, 40 }};
static const abdlop_params_t params4 = {{ params4_ring, params4_dcomp, 20, 47, 0, 2, 12, params4_Bsq, 1, 8, 5, 140, 1, 15, params4_scM1, params4_stdev1sq, 1, 15, params4_scM2, params4_stdev2sq}};

