// auto-generated by lnp-quad-codegen.sage from ../tests/lnp-quad-params3.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-6)
// protocol is simulatable under MLWE(23,5,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-146.0)
// 
// Ring
// degree d = 128
// modulus q = 9444732965739290427421, log(q) ~ 73.0
// factors q = q1
// 
// Compression
// D = 7
// gamma = 57588, log(gamma) ~ 15.813481
// m = (q-1)/gamma = 164005226188429715, log(m) ~ 57.186519
// 
// Dimensions of secrets
// s1: m1 = 10
// m: l = 0
// s2: m2 = 28
// 
// Size of secrets
// l2(s1) <= alpha = 107.33126
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Challenge space
// c uniform in [-omega,omega] = [-2,2], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 59
// 
// Standard deviations
// stdev1 = 50790.4, log(stdev1/1.55) = 15.0
// stdev2 = 25395.2, log(stdev2/1.55) = 14.0
// 
// Repetition rate
// M1 = 5.3392942
// M2 = 6.4860055
// total = 34.630692
// 
// Security
// MSIS dimension: 4
// MSIS root hermite factor: 1.0043978
// MLWE dimension: 23
// MLWE root hermite factor: 1.0043564
// 
// 50 bit moduli for degree 128: [1125899906840833, 1125899906826241, 1125899906824961, 1125899906822657]
// bit length of products: [49, 99, 149, 199]
// inverses: [1, -77158710720, -186207669797431, -233054335428326]

#include "lazer.h"
static const limb_t params3_q_limbs[] = {29UL, 512UL};
static const int_t params3_q = {{(limb_t *)params3_q_limbs, 2, 0}};
static const limb_t params3_qminus1_limbs[] = {28UL, 512UL};
static const int_t params3_qminus1 = {{(limb_t *)params3_qminus1_limbs, 2, 0}};
static const limb_t params3_m_limbs[] = {164005226188429715UL, 0UL};
static const int_t params3_m = {{(limb_t *)params3_m_limbs, 2, 0}};
static const limb_t params3_mby2_limbs[] = {0};
static const int_t params3_mby2 = {{(limb_t *)params3_mby2_limbs, 1, 0}};
static const limb_t params3_gamma_limbs[] = {57588UL, 0UL};
static const int_t params3_gamma = {{(limb_t *)params3_gamma_limbs, 2, 0}};
static const limb_t params3_gammaby2_limbs[] = {28794UL, 0UL};
static const int_t params3_gammaby2 = {{(limb_t *)params3_gammaby2_limbs, 2, 0}};
static const limb_t params3_pow2D_limbs[] = {128UL, 0UL};
static const int_t params3_pow2D = {{(limb_t *)params3_pow2D_limbs, 2, 0}};
static const limb_t params3_pow2Dby2_limbs[] = {64UL, 0UL};
static const int_t params3_pow2Dby2 = {{(limb_t *)params3_pow2Dby2_limbs, 2, 0}};
static const limb_t params3_Bsq_limbs[] = {8334972533909UL, 0UL, 0UL, 0UL};
static const int_t params3_Bsq = {{(limb_t *)params3_Bsq_limbs, 4, 0}};
static const limb_t params3_scM1_limbs[] = {9054606348222858233UL, 6258873423031413257UL, 5UL};
static const int_t params3_scM1 = {{(limb_t *)params3_scM1_limbs, 3, 0}};
static const limb_t params3_scM2_limbs[] = {8181658019854199047UL, 8965219983760634511UL, 6UL};
static const int_t params3_scM2 = {{(limb_t *)params3_scM2_limbs, 3, 0}};
static const limb_t params3_stdev1sq_limbs[] = {2579664732UL, 0UL, 0UL, 0UL};
static const int_t params3_stdev1sq = {{(limb_t *)params3_stdev1sq_limbs, 4, 0}};
static const limb_t params3_stdev2sq_limbs[] = {644916183UL, 0UL, 0UL, 0UL};
static const int_t params3_stdev2sq = {{(limb_t *)params3_stdev2sq_limbs, 4, 0}};
static const limb_t params3_inv2_limbs[] = {14UL, 256UL};
static const int_t params3_inv2 = {{(limb_t *)params3_inv2_limbs, 2, 1}};
static const limb_t params3_Pmodq_limbs[] = {6980892047629922943UL, 78UL};
static const int_t params3_Pmodq = {{(limb_t *)params3_Pmodq_limbs, 2, 0}};
static const limb_t params3_Ppmodq_0_limbs[] = {10949172136391650195UL, 238UL};
static const int_t params3_Ppmodq_0 = {{(limb_t *)params3_Ppmodq_0_limbs, 2, 1}};
static const limb_t params3_Ppmodq_1_limbs[] = {3462295020810966247UL, 39UL};
static const int_t params3_Ppmodq_1 = {{(limb_t *)params3_Ppmodq_1_limbs, 2, 0}};
static const limb_t params3_Ppmodq_2_limbs[] = {12102150227769583042UL, 124UL};
static const int_t params3_Ppmodq_2 = {{(limb_t *)params3_Ppmodq_2_limbs, 2, 1}};
static const limb_t params3_Ppmodq_3_limbs[] = {6914012357326625841UL, 120UL};
static const int_t params3_Ppmodq_3 = {{(limb_t *)params3_Ppmodq_3_limbs, 2, 1}};

static const int_srcptr params3_Ppmodq[] = {params3_Ppmodq_0, params3_Ppmodq_1, params3_Ppmodq_2, params3_Ppmodq_3};
static const polyring_t params3_ring = {{params3_q, 128, 74, 7, moduli_d128, 4, params3_Pmodq, params3_Ppmodq, params3_inv2}};
static const dcompress_params_t params3_dcomp = {{ params3_q, params3_qminus1, params3_m, params3_mby2, params3_gamma, params3_gammaby2, params3_pow2D, params3_pow2Dby2, 7, 1, 58 }};
static const abdlop_params_t params3 = {{ params3_ring, params3_dcomp, 10, 28, 0, 1, 4, params3_Bsq, 1, 2, 3, 59, 1, 15, params3_scM1, params3_stdev1sq, 1, 14, params3_scM2, params3_stdev2sq}};

