// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(149,15,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(4,420,2^(39.396456))
// 
// Ring
// degree d = 64
// modulus q = 1766847064778384329583297500742918515827483896875618958121606201292620101, log(q) ~ 240.0
// factors q = q1
// 
// Compression
// D = 17
// gamma = 62050490, log(gamma) ~ 25.886939
// 
// Dimensions of secrets
// s1: m1 = 256
// m: l = 0
// s2: m2 = 164
// 
// Size of secrets
// l2(s1) <= alpha = 128.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [256], bounds: [128.0])
// approximate infinity: yes (psi: 3357.3056, dimension: 128, bound: 8192.5)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 203161.6, log(stdev1/1.55) = 17.0
// stdev2 = 12697.6, log(stdev2/1.55) = 13.0
// stdev3 = 12697.6, log(stdev3/1.55) = 13.0
// stdev4 = 812646.4, log(stdev4/1.55) = 19.0
// 
// Repetition rate
// M1 = 3.2731865
// M2 = 1.8926526
// M3 = 1.0173384
// M4 = 1.0172724
// total = 6.4112742
// 
// Security
// MSIS dimension: 4
// MSIS root hermite factor: 1.0043871
// MLWE dimension: 149
// MLWE root hermite factor: 1.004382
// 
// Proof size
// ~ 94.3671875000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633, 1125899906826241, 1125899906824961, 1125899906822657, 1125899906820097, 1125899906819201, 1125899906817793, 1125899906815361]
// bit length of products: [49, 99, 149, 199, 249, 299, 349, 399, 449, 499]
// inverses: [1, -162099428551732, 296975494591860, 32272507837893, -134010426262513, -317852323291127, -420407837543331, -17461233410712, -75308963507827, 553067999971776]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {325UL, 0UL, 0UL, 281474976710656UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 4, 0}};
static const limb_t _param_qminus1_limbs[] = {324UL, 0UL, 0UL, 281474976710656UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 4, 0}};
static const limb_t _param_m_limbs[] = {17236735215102513418UL, 9875504923826576035UL, 16279649584701508243UL, 4536224UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 4, 0}};
static const limb_t _param_mby2_limbs[] = {17841739644406032517UL, 14161124498768063825UL, 8139824792350754121UL, 2268112UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 4, 0}};
static const limb_t _param_gamma_limbs[] = {62050490UL, 0UL, 0UL, 0UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 4, 0}};
static const limb_t _param_gammaby2_limbs[] = {31025245UL, 0UL, 0UL, 0UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 4, 0}};
static const limb_t _param_pow2D_limbs[] = {131072UL, 0UL, 0UL, 0UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 4, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {65536UL, 0UL, 0UL, 0UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 4, 0}};
static const limb_t _param_Bsq_limbs[] = {416082105787457450UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 8, 0}};
static const limb_t _param_scM1_limbs[] = {9893745843492854333UL, 5039401612991493220UL, 3UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {7885260774978684056UL, 16466534114149545469UL, 1UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {6853834115236121003UL, 319836111374498275UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {15194368311518125338UL, 318620152316739781UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {41274635715UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 8, 0}};
static const limb_t _param_stdev2sq_limbs[] = {161229046UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 8, 0}};
static const limb_t _param_stdev3sq_limbs[] = {161229046UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 8, 0}};
static const limb_t _param_stdev4sq_limbs[] = {660394171433UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 8, 0}};
static const limb_t _param_inv2_limbs[] = {162UL, 0UL, 0UL, 140737488355328UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 4, 1}};
static const limb_t _param_inv4_limbs[] = {81UL, 0UL, 0UL, 70368744177664UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 4, 1}};
static const unsigned int _param_n[1] = {256};
static const limb_t _param_Bz3sqr_limbs[] = {111012260217UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 8, 0}};
static const limb_t _param_Bz4_limbs[] = {13002342UL, 0UL, 0UL, 0UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 4, 0}};
static const limb_t _param_Pmodq_limbs[] = {13398380815092506083UL, 7298662820824383713UL, 11669861707847205711UL, 96450190052079UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 4, 0}};
static const limb_t _param_l2Bsq0_limbs[] = {16384UL, 0UL, 0UL, 0UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 4, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {9583451888392211591UL, 11650323154586640860UL, 11287600894203732774UL, 129831307148963UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 4, 0}};
static const limb_t _param_Ppmodq_1_limbs[] = {11939554434635216927UL, 12153396075967196208UL, 13376446272614204703UL, 63539586613882UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 4, 0}};
static const limb_t _param_Ppmodq_2_limbs[] = {6572556310776800390UL, 17503309403198608935UL, 16623607553647052303UL, 124012953026330UL};
static const int_t _param_Ppmodq_2 = {{(limb_t *)_param_Ppmodq_2_limbs, 4, 1}};
static const limb_t _param_Ppmodq_3_limbs[] = {4792780913856083705UL, 5611377498945948951UL, 2964736514848267004UL, 7301641547445UL};
static const int_t _param_Ppmodq_3 = {{(limb_t *)_param_Ppmodq_3_limbs, 4, 1}};
static const limb_t _param_Ppmodq_4_limbs[] = {2896799401480847424UL, 1601315408333797538UL, 2963059590877356620UL, 95328038085353UL};
static const int_t _param_Ppmodq_4 = {{(limb_t *)_param_Ppmodq_4_limbs, 4, 1}};
static const limb_t _param_Ppmodq_5_limbs[] = {14177180751811327607UL, 8537715305707830319UL, 14110726157247873092UL, 130614460602992UL};
static const int_t _param_Ppmodq_5 = {{(limb_t *)_param_Ppmodq_5_limbs, 4, 1}};
static const limb_t _param_Ppmodq_6_limbs[] = {7999964493179309507UL, 16037402735244920904UL, 128853736542928693UL, 44328345176335UL};
static const int_t _param_Ppmodq_6 = {{(limb_t *)_param_Ppmodq_6_limbs, 4, 0}};
static const limb_t _param_Ppmodq_7_limbs[] = {10104750169377134564UL, 15856940822628597077UL, 8644620065996853322UL, 75088816763773UL};
static const int_t _param_Ppmodq_7 = {{(limb_t *)_param_Ppmodq_7_limbs, 4, 0}};
static const limb_t _param_Ppmodq_8_limbs[] = {7540744963873476760UL, 6482742761888821390UL, 8496353126532243437UL, 34874055794605UL};
static const int_t _param_Ppmodq_8 = {{(limb_t *)_param_Ppmodq_8_limbs, 4, 0}};
static const limb_t _param_Ppmodq_9_limbs[] = {10065011708407245468UL, 5256406339287747886UL, 10458858276602787099UL, 105263883132849UL};
static const int_t _param_Ppmodq_9 = {{(limb_t *)_param_Ppmodq_9_limbs, 4, 1}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1, _param_Ppmodq_2, _param_Ppmodq_3, _param_Ppmodq_4, _param_Ppmodq_5, _param_Ppmodq_6, _param_Ppmodq_7, _param_Ppmodq_8, _param_Ppmodq_9};
static const polyring_t _param_ring = {{_param_q, 64, 241, 6, moduli_d64, 10, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 17, 0, 215 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 257, 164, 0, 11, 4, _param_Bsq, 1, 8, 5, 140, 1, 17, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 257, 164, 9, 2, 4, _param_Bsq, 1, 8, 5, 140, 1, 17, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 257, 164, 10, 1, 4, _param_Bsq, 1, 8, 5, 140, 1, 17, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 2}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 0, _param_n, 128, 1, 257, 2, 13, _param_scM3, _param_stdev3sq, 2, 19, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 96632UL }};

static const unsigned int param_Es0[256] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255};
static const unsigned int *param_Es[1] = { param_Es0, };
static const unsigned int param_Es_nrows[1] = {256};

static const limb_t param_p_limbs[] = {18446744073709551361UL, 18446744073709551615UL, 18446744073709551615UL, 4194303UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 4, 0}};
static const limb_t param_pinv_limbs[] = {800146402405188813UL, 5378150730096558262UL, 9406053517227734099UL, 3219864499011UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 4, 1}};
static const unsigned int param_s1_indices[64] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63};
static const lin_params_t param = {{ _param, 256, param_p, param_pinv, 4, param_s1_indices, 64, NULL, 0,  NULL, 0, param_Es, param_Es_nrows, NULL, NULL }};

