// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(23,31,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(19,86,2^(33.173537))
// 
// Ring
// degree d = 64
// modulus q = 68719476853, log(q) ~ 36.0
// factors q = q1
// 
// Compression
// D = 9
// gamma = 218588, log(gamma) ~ 17.737855
// 
// Dimensions of secrets
// s1: m1 = 32
// m: l = 0
// s2: m2 = 54
// 
// Size of secrets
// l2(s1) <= alpha = 55.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [32], bounds: [54.305801])
// approximate infinity: yes (psi: 3357.6996, dimension: 16, bound: 2047.8847)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 101580.8, log(stdev1/1.55) = 16.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 6348.8, log(stdev3/1.55) = 12.0
// stdev4 = 203161.6, log(stdev4/1.55) = 17.0
// 
// Repetition rate
// M1 = 2.7934649
// M2 = 2.316982
// M3 = 1.0126757
// M4 = 1.0172683
// total = 6.6676345
// 
// Security
// MSIS dimension: 19
// MSIS root hermite factor: 1.0043658
// MLWE dimension: 23
// MLWE root hermite factor: 1.004348
// 
// Proof size
// ~ 19.2636718750000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937]
// bit length of products: [49, 99]
// inverses: [1, -162099428551732]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {68719476853UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 1, 0}};
static const limb_t _param_qminus1_limbs[] = {68719476852UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 1, 0}};
static const limb_t _param_m_limbs[] = {314379UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 1, 0}};
static const limb_t _param_mby2_limbs[] = {314379/2UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 1, 0}};
static const limb_t _param_gamma_limbs[] = {218588UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 1, 0}};
static const limb_t _param_gammaby2_limbs[] = {109294UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 1, 0}};
static const limb_t _param_pow2D_limbs[] = {512UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 1, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {256UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 1, 0}};
static const limb_t _param_Bsq_limbs[] = {31234963027316UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 2, 0}};
static const limb_t _param_scM1_limbs[] = {14923953549232200436UL, 14636844008476446150UL, 2UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {16587662842483214675UL, 5847285564330895312UL, 2UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {14766196062294935536UL, 233824935767127237UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {10522517254239783054UL, 318544733832791720UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {10318658929UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 2, 0}};
static const limb_t _param_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 2, 0}};
static const limb_t _param_stdev3sq_limbs[] = {40307261UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 2, 0}};
static const limb_t _param_stdev4sq_limbs[] = {41274635715UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 2, 0}};
static const limb_t _param_inv2_limbs[] = {34359738426UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 1, 1}};
static const limb_t _param_inv4_limbs[] = {17179869213UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 1, 1}};
static const unsigned int _param_n[1] = {32};
static const limb_t _param_Bz3sqr_limbs[] = {27753065054UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 2, 0}};
static const limb_t _param_Bz4_limbs[] = {3250585UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 1, 0}};
static const limb_t _param_Pmodq_limbs[] = {27649976877UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 1, 1}};
static const limb_t _param_l2Bsq0_limbs[] = {2949UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 1, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {1919615UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 1, 1}};
static const limb_t _param_Ppmodq_1_limbs[] = {1918719UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 1, 1}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1};
static const polyring_t _param_ring = {{_param_q, 64, 37, 6, moduli_d64, 2, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 9, 1, 19 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 33, 54, 0, 12, 19, _param_Bsq, 1, 8, 5, 140, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 33, 54, 9, 3, 19, _param_Bsq, 1, 8, 5, 140, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 33, 54, 11, 1, 19, _param_Bsq, 1, 8, 5, 140, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 4}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 0, _param_n, 16, 1, 33, 2, 12, _param_scM3, _param_stdev3sq, 2, 17, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 19726UL }};

static const unsigned int param_Es0[32] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31};
static const unsigned int *param_Es[1] = { param_Es0, };
static const unsigned int param_Es_nrows[1] = {32};

static const limb_t param_p_limbs[] = {3329UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 1, 0}};
static const limb_t param_pinv_limbs[] = {10321339269UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 1, 0}};
static const unsigned int param_s1_indices[8] = {0, 1, 2, 3, 4, 5, 6, 7};
static const lin_params_t param = {{ _param, 256, param_p, param_pinv, 4, param_s1_indices, 8, NULL, 0,  NULL, 0, param_Es, param_Es_nrows, NULL, NULL }};

