// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(26,29,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(17,87,2^(33.528703))
// 
// Ring
// degree d = 64
// modulus q = 2199023255677, log(q) ~ 41.0
// factors q = q1
// 
// Compression
// D = 9
// gamma = 434382, log(gamma) ~ 18.728605
// 
// Dimensions of secrets
// s1: m1 = 32
// m: l = 0
// s2: m2 = 55
// 
// Size of secrets
// l2(s1) <= alpha = 55.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [32], bounds: [54.305801])
// approximate infinity: yes (psi: 3958.0174, dimension: 16, bound: 55592.935)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 101580.8, log(stdev1/1.55) = 16.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 6348.8, log(stdev3/1.55) = 12.0
// stdev4 = 6501171.2, log(stdev4/1.55) = 22.0
// 
// Repetition rate
// M1 = 2.7934649
// M2 = 2.3533173
// M3 = 1.0126757
// M4 = 1.0123975
// total = 6.7397711
// 
// Security
// MSIS dimension: 17
// MSIS root hermite factor: 1.0043766
// MLWE dimension: 26
// MLWE root hermite factor: 1.0043734
// 
// Proof size
// ~ 20.5332031250000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937]
// bit length of products: [49, 99]
// inverses: [1, -162099428551732]

#include "lazer.h"
static const limb_t _params_q_limbs[] = {2199023255677UL};
static const int_t _params_q = {{(limb_t *)_params_q_limbs, 1, 0}};
static const limb_t _params_qminus1_limbs[] = {2199023255676UL};
static const int_t _params_qminus1 = {{(limb_t *)_params_qminus1_limbs, 1, 0}};
static const limb_t _params_m_limbs[] = {5062418UL};
static const int_t _params_m = {{(limb_t *)_params_m_limbs, 1, 0}};
static const limb_t _params_mby2_limbs[] = {2531209UL};
static const int_t _params_mby2 = {{(limb_t *)_params_mby2_limbs, 1, 0}};
static const limb_t _params_gamma_limbs[] = {434382UL};
static const int_t _params_gamma = {{(limb_t *)_params_gamma_limbs, 1, 0}};
static const limb_t _params_gammaby2_limbs[] = {217191UL};
static const int_t _params_gammaby2 = {{(limb_t *)_params_gammaby2_limbs, 1, 0}};
static const limb_t _params_pow2D_limbs[] = {512UL};
static const int_t _params_pow2D = {{(limb_t *)_params_pow2D_limbs, 1, 0}};
static const limb_t _params_pow2Dby2_limbs[] = {256UL};
static const int_t _params_pow2Dby2 = {{(limb_t *)_params_pow2Dby2_limbs, 1, 0}};
static const limb_t _params_Bsq_limbs[] = {78834554904582UL, 0UL};
static const int_t _params_Bsq = {{(limb_t *)_params_Bsq_limbs, 2, 0}};
static const limb_t _params_scM1_limbs[] = {14923953549232200436UL, 14636844008476446150UL, 2UL};
static const int_t _params_scM1 = {{(limb_t *)_params_scM1_limbs, 3, 0}};
static const limb_t _params_scM2_limbs[] = {608560980791652131UL, 6517553481399687226UL, 2UL};
static const int_t _params_scM2 = {{(limb_t *)_params_scM2_limbs, 3, 0}};
static const limb_t _params_scM3_limbs[] = {14766196062294935536UL, 233824935767127237UL, 1UL};
static const int_t _params_scM3 = {{(limb_t *)_params_scM3_limbs, 3, 0}};
static const limb_t _params_scM4_limbs[] = {13925546916997993317UL, 228693548972510154UL, 1UL};
static const int_t _params_scM4 = {{(limb_t *)_params_scM4_limbs, 3, 0}};
static const limb_t _params_stdev1sq_limbs[] = {10318658929UL, 0UL};
static const int_t _params_stdev1sq = {{(limb_t *)_params_stdev1sq_limbs, 2, 0}};
static const limb_t _params_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _params_stdev2sq = {{(limb_t *)_params_stdev2sq_limbs, 2, 0}};
static const limb_t _params_stdev3sq_limbs[] = {40307261UL, 0UL};
static const int_t _params_stdev3sq = {{(limb_t *)_params_stdev3sq_limbs, 2, 0}};
static const limb_t _params_stdev4sq_limbs[] = {42265226971709UL, 0UL};
static const int_t _params_stdev4sq = {{(limb_t *)_params_stdev4sq_limbs, 2, 0}};
static const limb_t _params_inv2_limbs[] = {1099511627838UL};
static const int_t _params_inv2 = {{(limb_t *)_params_inv2_limbs, 1, 1}};
static const limb_t _params_inv4_limbs[] = {549755813919UL};
static const int_t _params_inv4 = {{(limb_t *)_params_inv4_limbs, 1, 1}};
static const unsigned int _params_n[1] = {32};
static const limb_t _params_Bz3sqr_limbs[] = {27753065054UL, 0UL};
static const int_t _params_Bz3sqr = {{(limb_t *)_params_Bz3sqr_limbs, 2, 0}};
static const limb_t _params_Bz4_limbs[] = {104018739UL};
static const int_t _params_Bz4 = {{(limb_t *)_params_Bz4_limbs, 1, 0}};
static const limb_t _params_Pmodq_limbs[] = {4387404417UL};
static const int_t _params_Pmodq = {{(limb_t *)_params_Pmodq_limbs, 1, 0}};
static const limb_t _params_l2Bsq0_limbs[] = {2949UL};
static const int_t _params_l2Bsq0 = {{(limb_t *)_params_l2Bsq0_limbs, 1, 0}};
static const limb_t _params_Ppmodq_0_limbs[] = {66687UL};
static const int_t _params_Ppmodq_0 = {{(limb_t *)_params_Ppmodq_0_limbs, 1, 1}};
static const limb_t _params_Ppmodq_1_limbs[] = {65791UL};
static const int_t _params_Ppmodq_1 = {{(limb_t *)_params_Ppmodq_1_limbs, 1, 1}};
static const int_srcptr _params_l2Bsq[] = {_params_l2Bsq0};
static const int_srcptr _params_Ppmodq[] = {_params_Ppmodq_0, _params_Ppmodq_1};
static const polyring_t _params_ring = {{_params_q, 64, 42, 6, moduli_d64, 2, _params_Pmodq, _params_Ppmodq, _params_inv2}};
static const dcompress_params_t _params_dcomp = {{ _params_q, _params_qminus1, _params_m, _params_mby2, _params_gamma, _params_gammaby2, _params_pow2D, _params_pow2Dby2, 9, 0, 23 }};
static const abdlop_params_t _params_tbox = {{ _params_ring, _params_dcomp, 33, 55, 0, 12, 17, _params_Bsq, 1, 8, 5, 140, 1, 16, _params_scM1, _params_stdev1sq, 2, 12, _params_scM2, _params_stdev2sq}};
static const abdlop_params_t _params_quad_eval_ = {{ _params_ring, _params_dcomp, 33, 55, 9, 3, 17, _params_Bsq, 1, 8, 5, 140, 1, 16, _params_scM1, _params_stdev1sq, 2, 12, _params_scM2, _params_stdev2sq}};
static const abdlop_params_t _params_quad_many_ = {{ _params_ring, _params_dcomp, 33, 55, 11, 1, 17, _params_Bsq, 1, 8, 5, 140, 1, 16, _params_scM1, _params_stdev1sq, 2, 12, _params_scM2, _params_stdev2sq}};
static const lnp_quad_eval_params_t _params_quad_eval = {{ _params_quad_eval_, _params_quad_many_, 4}};
static const lnp_tbox_params_t _params = {{ _params_tbox, _params_quad_eval, 0, _params_n, 16, 1, 33, 2, 12, _params_scM3, _params_stdev3sq, 2, 22, _params_scM4, _params_stdev4sq, _params_Bz3sqr, _params_Bz4, &_params_l2Bsq[0], _params_inv4, 21026UL }};

static const unsigned int params_Es0[32] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31};
static const unsigned int *params_Es[1] = { params_Es0, };
static const unsigned int params_Es_nrows[1] = {32};

static const limb_t params_p_limbs[] = {3329UL};
static const int_t params_p = {{(limb_t *)params_p_limbs, 1, 0}};
static const limb_t params_pinv_limbs[] = {128149748153UL};
static const int_t params_pinv = {{(limb_t *)params_pinv_limbs, 1, 1}};
static const unsigned int params_s1_indices[8] = {0, 1, 2, 3, 4, 5, 6, 7};
static const lin_params_t params = {{ _params, 256, params_p, params_pinv, 4, params_s1_indices, 8, NULL, 0,  NULL, 0, params_Es, params_Es_nrows, NULL, NULL }};

