// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(32,32,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(20,104,2^(40.223956))
// 
// Ring
// degree d = 64
// modulus q = 1125899906843189, log(q) ~ 50.0
// factors q = q1
// 
// Compression
// D = 15
// gamma = 30988582, log(gamma) ~ 24.885233
// 
// Dimensions of secrets
// s1: m1 = 40
// m: l = 0
// s2: m2 = 64
// 
// Size of secrets
// l2(s1) <= alpha = 5835.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 8)
// exact euclidean: yes (dimensions: [16, 16], bounds: [109.0, 5833.9289])
// approximate infinity: yes (psi: 3772.599, dimension: 8, bound: 7465632.9)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 13002342.4, log(stdev1/1.55) = 23.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 406323.2, log(stdev3/1.55) = 18.0
// stdev4 = 832149913.6, log(stdev4/1.55) = 29.0
// 
// Repetition rate
// M1 = 2.3213536
// M2 = 2.707079
// M3 = 1.0353595
// M4 = 1.0136546
// total = 6.5951303
// 
// Security
// MSIS dimension: 20
// MSIS root hermite factor: 1.0043904
// MLWE dimension: 32
// MLWE root hermite factor: 1.0043146
// 
// Proof size
// ~ 27.6718750000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _p2_params_q_limbs[] = {1125899906843189UL};
static const int_t _p2_params_q = {{(limb_t *)_p2_params_q_limbs, 1, 0}};
static const limb_t _p2_params_qminus1_limbs[] = {1125899906843188UL};
static const int_t _p2_params_qminus1 = {{(limb_t *)_p2_params_qminus1_limbs, 1, 0}};
static const limb_t _p2_params_m_limbs[] = {36332734UL};
static const int_t _p2_params_m = {{(limb_t *)_p2_params_m_limbs, 1, 0}};
static const limb_t _p2_params_mby2_limbs[] = {18166367UL};
static const int_t _p2_params_mby2 = {{(limb_t *)_p2_params_mby2_limbs, 1, 0}};
static const limb_t _p2_params_gamma_limbs[] = {30988582UL};
static const int_t _p2_params_gamma = {{(limb_t *)_p2_params_gamma_limbs, 1, 0}};
static const limb_t _p2_params_gammaby2_limbs[] = {15494291UL};
static const int_t _p2_params_gammaby2 = {{(limb_t *)_p2_params_gammaby2_limbs, 1, 0}};
static const limb_t _p2_params_pow2D_limbs[] = {32768UL};
static const int_t _p2_params_pow2D = {{(limb_t *)_p2_params_pow2D_limbs, 1, 0}};
static const limb_t _p2_params_pow2Dby2_limbs[] = {16384UL};
static const int_t _p2_params_pow2Dby2 = {{(limb_t *)_p2_params_pow2Dby2_limbs, 1, 0}};
static const limb_t _p2_params_Bsq_limbs[] = {405742612515304607UL, 0UL};
static const int_t _p2_params_Bsq = {{(limb_t *)_p2_params_Bsq_limbs, 2, 0}};
static const limb_t _p2_params_scM1_limbs[] = {15129543225641675539UL, 5927927291014142839UL, 2UL};
static const int_t _p2_params_scM1 = {{(limb_t *)_p2_params_scM1_limbs, 3, 0}};
static const limb_t _p2_params_scM2_limbs[] = {15002606599518648986UL, 13043305028329312333UL, 2UL};
static const int_t _p2_params_scM2 = {{(limb_t *)_p2_params_scM2_limbs, 3, 0}};
static const limb_t _p2_params_scM3_limbs[] = {15855013352410596805UL, 652267627509959950UL, 1UL};
static const int_t _p2_params_scM3 = {{(limb_t *)_p2_params_scM3_limbs, 3, 0}};
static const limb_t _p2_params_scM4_limbs[] = {4563597834133008302UL, 251882544574904658UL, 1UL};
static const int_t _p2_params_scM4 = {{(limb_t *)_p2_params_scM4_limbs, 3, 0}};
static const limb_t _p2_params_stdev1sq_limbs[] = {169060907886838UL, 0UL};
static const int_t _p2_params_stdev1sq = {{(limb_t *)_p2_params_stdev1sq_limbs, 2, 0}};
static const limb_t _p2_params_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _p2_params_stdev2sq = {{(limb_t *)_p2_params_stdev2sq_limbs, 2, 0}};
static const limb_t _p2_params_stdev3sq_limbs[] = {165098542858UL, 0UL};
static const int_t _p2_params_stdev3sq = {{(limb_t *)_p2_params_stdev3sq_limbs, 2, 0}};
static const limb_t _p2_params_stdev4sq_limbs[] = {692473478704487465UL, 0UL};
static const int_t _p2_params_stdev4sq = {{(limb_t *)_p2_params_stdev4sq_limbs, 2, 0}};
static const limb_t _p2_params_inv2_limbs[] = {562949953421594UL};
static const int_t _p2_params_inv2 = {{(limb_t *)_p2_params_inv2_limbs, 1, 1}};
static const limb_t _p2_params_inv4_limbs[] = {281474976710797UL};
static const int_t _p2_params_inv4 = {{(limb_t *)_p2_params_inv4_limbs, 1, 1}};
static const unsigned int _p2_params_n[2] = {16, 16};
static const limb_t _p2_params_Bz3sqr_limbs[] = {113676554463109UL, 0UL};
static const int_t _p2_params_Bz3sqr = {{(limb_t *)_p2_params_Bz3sqr_limbs, 2, 0}};
static const limb_t _p2_params_Bz4_limbs[] = {13314398617UL};
static const int_t _p2_params_Bz4 = {{(limb_t *)_p2_params_Bz4_limbs, 1, 0}};
static const limb_t _p2_params_Pmodq_limbs[] = {42568471872UL};
static const int_t _p2_params_Pmodq = {{(limb_t *)_p2_params_Pmodq_limbs, 1, 1}};
static const limb_t _p2_params_l2Bsq0_limbs[] = {11881UL};
static const int_t _p2_params_l2Bsq0 = {{(limb_t *)_p2_params_l2Bsq0_limbs, 1, 0}};
static const limb_t _p2_params_l2Bsq1_limbs[] = {34034726UL};
static const int_t _p2_params_l2Bsq1 = {{(limb_t *)_p2_params_l2Bsq1_limbs, 1, 0}};
static const limb_t _p2_params_Ppmodq_0_limbs[] = {18068112UL};
static const int_t _p2_params_Ppmodq_0 = {{(limb_t *)_p2_params_Ppmodq_0_limbs, 1, 0}};
static const limb_t _p2_params_Ppmodq_1_limbs[] = {13089936UL};
static const int_t _p2_params_Ppmodq_1 = {{(limb_t *)_p2_params_Ppmodq_1_limbs, 1, 0}};
static const limb_t _p2_params_Ppmodq_2_limbs[] = {7661712UL};
static const int_t _p2_params_Ppmodq_2 = {{(limb_t *)_p2_params_Ppmodq_2_limbs, 1, 0}};
static const int_srcptr _p2_params_l2Bsq[] = {_p2_params_l2Bsq0, _p2_params_l2Bsq1};
static const int_srcptr _p2_params_Ppmodq[] = {_p2_params_Ppmodq_0, _p2_params_Ppmodq_1, _p2_params_Ppmodq_2};
static const polyring_t _p2_params_ring = {{_p2_params_q, 64, 51, 6, moduli_d64, 3, _p2_params_Pmodq, _p2_params_Ppmodq, _p2_params_inv2}};
static const dcompress_params_t _p2_params_dcomp = {{ _p2_params_q, _p2_params_qminus1, _p2_params_m, _p2_params_mby2, _p2_params_gamma, _p2_params_gammaby2, _p2_params_pow2D, _p2_params_pow2Dby2, 15, 0, 26 }};
static const abdlop_params_t _p2_params_tbox = {{ _p2_params_ring, _p2_params_dcomp, 42, 64, 0, 12, 20, _p2_params_Bsq, 1, 8, 5, 140, 1, 23, _p2_params_scM1, _p2_params_stdev1sq, 2, 12, _p2_params_scM2, _p2_params_stdev2sq}};
static const abdlop_params_t _p2_params_quad_eval_ = {{ _p2_params_ring, _p2_params_dcomp, 42, 64, 9, 3, 20, _p2_params_Bsq, 1, 8, 5, 140, 1, 23, _p2_params_scM1, _p2_params_stdev1sq, 2, 12, _p2_params_scM2, _p2_params_stdev2sq}};
static const abdlop_params_t _p2_params_quad_many_ = {{ _p2_params_ring, _p2_params_dcomp, 42, 64, 11, 1, 20, _p2_params_Bsq, 1, 8, 5, 140, 1, 23, _p2_params_scM1, _p2_params_stdev1sq, 2, 12, _p2_params_scM2, _p2_params_stdev2sq}};
static const lnp_quad_eval_params_t _p2_params_quad_eval = {{ _p2_params_quad_eval_, _p2_params_quad_many_, 4}};
static const lnp_tbox_params_t _p2_params = {{ _p2_params_tbox, _p2_params_quad_eval, 8, _p2_params_n, 8, 2, 42, 2, 18, _p2_params_scM3, _p2_params_stdev3sq, 2, 29, _p2_params_scM4, _p2_params_stdev4sq, _p2_params_Bz3sqr, _p2_params_Bz4, &_p2_params_l2Bsq[0], _p2_params_inv4, 28336UL }};

static const unsigned int p2_params_Ps[8] = {16, 17, 18, 19, 20, 21, 22, 23};
static const unsigned int p2_params_Es0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const unsigned int p2_params_Es1[16] = {24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const unsigned int *p2_params_Es[2] = { p2_params_Es0, p2_params_Es1, };
static const unsigned int p2_params_Es_nrows[2] = {16, 16};

static const limb_t p2_params_p_limbs[] = {12289UL};
static const int_t p2_params_p = {{(limb_t *)p2_params_p_limbs, 1, 0}};
static const limb_t p2_params_pinv_limbs[] = {60834692663673UL};
static const int_t p2_params_pinv = {{(limb_t *)p2_params_pinv_limbs, 1, 0}};
static const unsigned int p2_params_s1_indices[5] = {0, 1, 2, 3, 4};
static const lin_params_t p2_params = {{ _p2_params, 512, p2_params_p, p2_params_pinv, 8, p2_params_s1_indices, 5, NULL, 0,  p2_params_Ps, 8, p2_params_Es, p2_params_Es_nrows, NULL, NULL }};

