#ifndef LAZER_CONFIGOPTS_H
#define LAZER_CONFIGOPTS_H

#define TARGET_GENERIC 0
#define TARGET_AMD64 1

#define RNG_SHAKE128 0
#define RNG_AES256CTR 1

#define ASSERT_DISABLED 0
#define ASSERT_ENABLED 1

#define TIMERS_DISABLED 0
#define TIMERS_ENABLED 1

#define DEBUGINFO_DISABLED 0
#define DEBUGINFO_ENABLED 1

#define VALGRIND_DISABLED 0
#define VALGRIND_ENABLED 1

#endif
